import jsonpath
import json
obj = json.load(open('../json/store.json','r',encoding='utf-8'))
author_list = jsonpath.jsonpath(obj,'$.store.book[*].author')
print(author_list)
al = jsonpath.jsonpath(obj,'$..author')
print(al)
all_list = jsonpath.jsonpath(obj,'$.store.*')
print(all_list)
price_list = jsonpath.jsonpath(obj,'$.store..price')
print(price_list)
book3 = jsonpath.jsonpath(obj,'$..book[2]')
print(book3)
book_last = jsonpath.jsonpath(obj,'$..book[(@.length-1)]')
print(book_last)
book1and2 = jsonpath.jsonpath(obj,'$..book[:2]')
print(book1and2)
book1and2 = jsonpath.jsonpath(obj,'$..book[0,1]')
print(book1and2)
isbn = jsonpath.jsonpath(obj,'$..book[?(@.isbn)]')
print(isbn)
price_less = jsonpath.jsonpath(obj,'$..book[?(@.price<10)]')
print(price_less)
all_ele = jsonpath.jsonpath(obj,'$..*')
print(all_ele)